params:
  num_image_pairs: 25
  num_matches_per_image_pair: 100

networks:
  rope_nonrigid_412vert_3:                                                                                                
    path_to_network_params: code/data_volume/pdc_synthetic_2/trained_models/tutorials/rope_nonrigid_412vert_3/003500.pth
  tier3_oracle_1824_3:                                                                                                
    path_to_network_params: code/data_volume/fabric_data/trained_models/tutorials/tier3_oracle_1824_3/003500.pth
  tier3_oracle_1824_depth_3:                                                                                                
    path_to_network_params: code/data_volume/fabric_data/trained_models/tutorials/tier3_oracle_1824_depth_3/003500.pth
dataset: [] # which dataset to use, not used for now


output_dir: code/data_volume/fabric_data/analysis
